FROM grafana/grafana
COPY ./Dashboards.yaml /etc/grafana/provisioning/dashboards/
COPY ./Datasource.yaml /etc/grafana/provisioning/datasources/
COPY ./dashboards/default.json /etc/grafana/provisioning/dashboards/
