global:
  scrape_interval: 5s
  evaluation_interval: 10s

rule_files:
- "etc/prometheus/rules.yml"
  
scrape_configs:
- job_name: demo
  metrics_path: /metrics
  static_configs:
    - targets:
      - main:5000
      - worker_1:5000
      - worker_2:5000
      - worker_3:5000
      - worker_4:5000
      - worker_5:5000
      - worker_6:5000
      - worker_7:5000
      - worker_8:5000
      - worker_9:5000